# Site settings
title: Flatiron First Timer
header-img: img/home-bg.png
email: stephanie.carrizales.aya@gmail.com
copyright_name: stephcarrizales
description: > # this means to ignore newlines until "baseurl:"
  My Journey with Code
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  stephcarrizales
learn_profile: stephcarrizales
email_username: stephanie.carrizales.aya@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
